trigger e2etests

diff --git a/.github/workflows/ecs_deploy.yaml b/.github/workflows/ecs_deploy.yaml
--- a/.github/workflows/ecs_deploy.yaml
+++ b/.github/workflows/ecs_deploy.yaml
@@ -124,3 +124,25 @@ jobs:
           task-definition: task-definition.json
           wait-for-service-stability: false
           wait-for-minutes: 5
+
+  run-integration-tests:
+    name: Trigger E2Etests
+    needs: [deploy]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Trigger E2Etests
+        run: |
+          response=$(curl -L -X POST -H "Accept: application/vnd.github+json" \
+          -H "Authorization: Bearer ${{secrets.GH_ACTION_TRIGGER_TOKEN }}" \
+          -H "X-GitHub-Api-Version: 2022-11-28" \
+          https://api.github.com/repos/blndgs/e2etests/actions/workflows/test-infra.yml/dispatches -d '{"ref":"main"}' \
+          -w "%{http_code}")
+
+          http_code=$(echo "$response" | tail -n1)
+
+          if [ "$http_code" -le 204 ]; then
+            echo "Workflow dispatch successful! (Status code: $http_code)"
+          else
+            echo "Workflow dispatch failed. (Status code: $http_code)"
+            exit 128;
+          fi
